name: build-ui

on:
  push:
    branches:
      - main
    paths:
      - "ui/**"
      - ".github/workflows/build-ui.yml"
  pull_request:
    branches:
      - main
    paths:
      - "ui/**"
      - ".github/workflows/build-ui.yml"
  workflow_dispatch: {}
  workflow_run:
    workflows: [build-wasm]
    types: [completed]

env:
  VERSION: 0.1.${{ github.run_number }}

jobs:
  build-ui:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'

    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x (ui)
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install Dependencies
        run: yarn

      - name: change publicPath
        if: false
        run: |
          sed -i "s/\/\/ publicPath: '\/'/publicPath: 'halo2visualizer'/" ui/quasar.config.js

      - name: Download wasm
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: wasm
          workflow: build-wasm.yml
          path: ui/src/transpiler

      - name: Build
        run: |
          yarn build:ui

      - name: version
        run: |
          echo ${VERSION}>ui/dist/spa/version.txt

      - uses: actions/upload-artifact@v3
        with:
          name: ui
          path: ui/dist/spa